Repository nodejs/node-gyp, pull requests merged in 2023-06, with the labels that each got.

#2857 win,install: only download target_arch node.lib
  lib/install.js
  package.json
  test/test-download.js
Labels: semver-major

#2872 lib: find python checks order changed on windows
  lib/find-python.js
Labels: Windows, Python, Upgrade to Python 3

#2644 Fix reading msvs version on Windows
  lib/configure.js
  lib/node-gyp.js
  test/test-options.js
Labels: Windows
