Repository nodejs/node-gyp, pull requests merged in 2024-04, with the labels that each got.

#3010 README.md: Installation -- Python >= v3.12 requires `node-gyp` >= v10
  README.md
Labels: Python, ERR! node-gyp -v < v10.x.x

#3008 Add Chocolatey Guide for node-gyp on Windows
  README.md
Labels: Windows

#3011 GitHub Actions: npm test is failing Windows tests on M1 Macs
  .github/workflows/tests.yml
  test/test-find-visualstudio.js
Labels: Arm, macOS
